name: Python unit-tests

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install .
        pip install pytest
    - name: Test
      run: DFLOW_MODE=debug pytest -vs tests
